---
apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
data:
  token: {{ .Values.secret.token | b64enc }}
  user_id: {{ .Values.secret.user_id | b64enc }}
  super_user_id: {{ .Values.secret.super_user_id | b64enc }}
