# Default values for name-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

secret:
  token: ""
  user_id: ""
  super_user_id: ""

image:
  name: name-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nodeSelector: {}

tolerations: []

affinity: {}
