apiVersion: apps/v1
kind: Deployment
metadata:
  name: "name-bot"
  namespace: "name-bot"
  labels:
    app: "name-bot"
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: "name-bot"
  template:
    metadata:
      labels:
        app: "name-bot"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: config
                  key: client_id
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config
                  key: token

            - name: USER_ID
              valueFrom:
                secretKeyRef:
                  name: config
                  key: user_id

            - name: SUPER_USER_ID
              valueFrom:
                secretKeyRef:
                  name: config
                  key: super_user_id

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
