---
apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: "name-bot"
type: Opaque
data:
  client_id: {{ .Values.secret.client_id | quote | b64enc }}
  token: {{ .Values.secret.token | quote  | b64enc }}
  user_id: {{ .Values.secret.user_id | quote | b64enc }}
  super_user_id: {{ .Values.secret.super_user_id | quote | b64enc }}
